### ISSUE TITLE
I can't install HPO.db.

### ISSUE THREAD

**Issue by xiexielaifang** [YuLab-SMU/HPO.db#4]
I Manually download HPO.db_0.99.2.tar.gz from the webpage which is https://bioconductor.org/packages/devel/data/annotation/html/HPO.db.html.

Then it runs like : 
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:
https://cran.rstudio.com/bin/windows/Rtools/
* installing *source* package 'HPO.db' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'HPO.db':
LoadNamespace () calculate 'HPO. db' onLoad fails, the details: 
Call:.updateHubDB(hub_bfc,.class, url, proxy, localHub) 
Error: Invalid Cache: sqlite file 
Hub has not been added to cache 
Run again with 'localHub=FALSE' 
Error: failed to load 
Stop execution 
ERROR: loading failed 
* removing  'D: / Program Files /R - 4.3.1 / library/HPO. Db' 
Warning in install.packages : 
Installation package 'HPO db_0. 99.2. Tar. Gz' exit status value is not zero.

Biobase                "Biobase"                "2.61.0"    
BiocFileCache          "BiocFileCache"          "2.9.1"     
BiocGenerics           "BiocGenerics"           "0.47.0"    
BiocManager            "BiocManager"            "1.30.22"   
BiocNeighbors          "BiocNeighbors"          "1.19.0"    
BiocParallel           "BiocParallel"           "1.35.4"    
BiocSingular           "BiocSingular"           "1.17.1"    
BiocVersion            "BiocVersion"            "3.18.0"    
Biostrings             "Biostrings"             "2.69.2"    

How can I solve the problem?

**Comment by huerqiang** [comment]
Try to install the Rtools and then reinstall the HPO.db package:
Please download and install the appropriate version of Rtools before proceeding:
https://cran.rstudio.com/bin/windows/Rtools/

**Comment by chzhylc** [comment]
I am faced with the same problem with xiexielaifang.
Thanks!
R version 4.3.1
RStudio-2023.09.0-463
rtools43-5550-5548

**Comment by zuiyanzuiyan** [comment]
I am faced with the same problem as well.

R version 4.3.1
RStudio-2023.09.0-463
rtools43-5550-5548

**Comment by huerqiang** [comment]
Please provide the complete error report.

**Comment by chzhylc** [comment]
> * HPO.db

> install.packages("C:/Users/Administrator/Desktop/HPO.db_0.99.2.tar.gz", repos = NULL, type = "source")
* installing *source* package 'HPO.db' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'HPO.db':
 .onLoad failed in loadNamespace() for 'HPO.db', details:
  call: .updateHubDB(hub_bfc, .class, url, proxy, localHub)
  error: Invalid Cache: sqlite file
  Hub has not been added to cache
  Run again with 'localHub=FALSE'
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Program Files/R/R-4.3.1/library/HPO.db'
Warning in install.packages :
  安装程序包‘C:/Users/Administrator/Desktop/HPO.db_0.99.2.tar.gz’时退出狀態的值不是0

**Comment by 2023BENBEN** [comment]
* installing *source* package 'HPO.db' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'HPO.db':
 .onLoad failed in loadNamespace() for 'HPO.db', details:
  call: .updateHubDB(hub_bfc, .class, url, proxy, localHub)
  error: Invalid Cache: sqlite file
  Hub has not been added to cache
  Run again with 'localHub=FALSE'
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Users/BEN/AppData/Local/R/win-library/4.3/HPO.db'

下载的程序包在
	‘C:\Users\BEN\AppData\Local\Temp\RtmpEnoPpm\downloaded_packages’里
Warning message:
In install.packages(...) : 安装程序包‘HPO.db’时退出狀態的值不是0

**Comment by 2023BENBEN** [comment]
I am faced with the same problem as well.

R version 4.3.1
RStudio-2023.09.0-463
rtools43-5863-5818

**Comment by huerqiang** [comment]
这是你的本地权限问题，跟HPO.db无关。你可以搜索下相关报错内容，网上有挺多解决方案。如果不想这么麻烦，也可以安装我整理好的本地版本：https://github.com/huerqiang/HPO.db_MPO.db

**Comment by 2023BENBEN** [comment]
HPO.db_0.99.0.tar.gz可以下载
MPO.db_0.99.0.tar.gz下载不了



在 2023-10-25 00:18:53，"Erqiang Hu" ***@***.***> 写道：

这是你的本地权限问题，跟HPO.db无关。你可以搜索下相关报错内容，网上有挺多解决方案。如果不想这么麻烦，也可以安装我整理好的本地版本：https://github.com/huerqiang/HPO.db_MPO.db

**Comment by 2023BENBEN** [comment]
都可以下载了，网速问题，谢谢老师



在 2023-10-25 00:41:12，"周华彬" ***@***.***> 写道：

HPO.db_0.99.0.tar.gz可以下载
MPO.db_0.99.0.tar.gz下载不了



在 2023-10-25 00:18:53，"Erqiang Hu" ***@***.***> 写道：

这是你的本地权限问题，跟HPO.db无关。你可以搜索下相关报错内容，网上有挺多解决方案。如果不想这么麻烦，也可以安装我整理好的本地版本：https://github.com/huerqiang/HPO.db_MPO.db

**Comment by 2023BENBEN** [comment]
Successfully installed, thank you!

**Comment by SHG369** [comment]
> 这是你的本地权限问题，跟HPO.db无关。你可以搜索下相关报错内容，网上有挺多解决方案。如果不想这么麻烦，也可以安装我整理好的本地版本：https://github.com/huerqiang/HPO.db_MPO.db

您好，按照您的方法下载了本地版本并安装好之后，library（）时没有报错，但我安装clusterprofiler等包时仍提示不存在HPD.db这个包：
载入需要的程辑包：clusterProfiler
Error: package or namespace load failed for ‘clusterProfiler’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 不存在叫‘HDO.db’这个名字的程辑包
载入需要的程辑包：enrichplot
Error: package or namespace load failed for ‘enrichplot’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 不存在叫‘HDO.db’这个名字的程辑包
载入需要的程辑包：tinyarray
Error: package or namespace load failed for ‘tinyarray’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 不存在叫‘HDO.db’这个名字的程辑包

**Comment by huerqiang** [comment]
那就是你没装上，请重启R后重新安装。

**Comment by SHG369** [comment]
> 那就是你没装上，请重启R后重新安装。

重启R后重新安装也提示已经安装上了：
> install.packages("C:/Program Files/R/R-4.3.1/library/HPO.db_MPO.db-main/HPO.db_MPO.db-main/HPO.db_0.99.0.tar.gz", repos = NULL, type = "source")
* installing *source* package 'HPO.db' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (HPO.db)
> library(HPO.db)
> library(clusterProfiler)
Error: package or namespace load failed for ‘clusterProfiler’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 不存在叫‘HDO.db’这个名字的程辑包

**Comment by chenx2gb** [comment]
好人啊，谢谢！！

**Comment by huerqiang** [comment]
@SHG369 你截图显示你装的是HPO.db，然而提示你缺少的是HDO.db。HDO.db还是挺好安装的，用常规方法就能装的上。

**Comment by chenx2gb** [comment]
您好，您的邮件我已收到

**Comment by JIN1997liu** [comment]
I'm trying to download HPO.db. I tried to open the link（https://github.com/huerqiang/HPO.db_MPO.db） but it won't download the file.

Webpage display
[View raw]
(Sorry about that, but we can’t show files that are this big right now.)

 I do not know why. Can someone email me a copy if it's convenient?  Email Address：1158647287@qq.com. Help me, please. Looking forward to your recovery!

**Comment by JIN1997liu** [comment]
> I'm trying to download HPO.db. I tried to open the link（[https://github.com/huerqiang/HPO.db_MPO.db）](https://github.com/huerqiang/HPO.db_MPO.db%EF%BC%89) but it won't download the file.
> 
> Webpage display [View raw] (Sorry about that, but we can’t show files that are this big right now.)
> 
> I do not know why. Can someone email me a copy if it's convenient? Email Address：[1158647287@qq.com](mailto:1158647287@qq.com). Help me, please. Looking forward to your recovery!

oh，no，Looking forward to your emails!

**Comment by SHG369** [comment]
非常感谢



---- 回复的原邮件 ----
| 发件人 | Erqiang ***@***.***> |
| 日期 | 2023年10月30日 23:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [YuLab-SMU/HPO.db] I can't install HPO.db. (Issue #4) |

@SHG369 你截图显示你装的是HPO.db，然而提示你缺少的是HDO.db。HDO.db还是挺好安装的，用常规方法就能装的上。

**Comment by SHG369** [comment]
明天早上提醒我，我会发给你



---- Replied Message ----
| From | ***@***.***> |
| Date | 10/30/2023 23:42 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [YuLab-SMU/HPO.db] I can't install HPO.db. (Issue #4) |

I'm trying to download HPO.db. I tried to open the link（https://github.com/huerqiang/HPO.db_MPO.db） but it won't download the file.

Webpage display [View raw] (Sorry about that, but we can’t show files that are this big right now.)

I do not know why. Can someone email me a copy if it's convenient? Email ***@***.*** Help me, please. Looking forward to your recovery!

oh，no，Looking forward to your emails!

**Comment by JIN1997liu** [comment]
> 明天早上提醒我，我会发给你

好的，非常感谢您

**Comment by 1127yangyuping** [comment]
非常感谢您

**Comment by chzhylc** [comment]
装上了，非常感谢您！

**Comment by qingyuyyy** [comment]
从Bioconductor上下载了HPO.db的源代码，但仍然无法在R中载入，请问能告诉我有什么问题吗？感谢！
以下是报错信息
install.packages("D:/R/HPO.db_0.99.2.tar.gz", repos = NULL, type = "source")* installing *source* package 'HPO.db' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'HPO.db':
 .onLoad failed in loadNamespace() for 'HPO.db', details:
  call: .updateHubDB(hub_bfc, .class, url, proxy, localHub)
  error: Invalid Cache: sqlite file
  Hub has not been added to cache
  Run again with 'localHub=FALSE'
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'D:/R/R-4.3.1/library/HPO.db'
Warning in install.packages :
  installation of package ‘D:/R/HPO.db_0.99.2.tar.gz’ had non-zero exit status

**Comment by 1127yangyuping** [comment]
这个老师的版本是0.99.0，你的版本是哦0.99.2，就是有可能适配性不太好，你下载这位老师的，解压下install就行了

**Comment by qingyuyyy** [comment]
因为我的R是4.3的，然后bioconductor上的版本是说0.99.2适配＞=4.3的R，所以我用的是直接在bioconductor上下载的。不过，感谢你的回答，我回去试试老师的看看



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月02日 16:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [YuLab-SMU/HPO.db] I can't install HPO.db. (Issue #4) |

这个老师的版本是0.99.0，你的版本是哦0.99.2，就是有可能适配性不太好，你下载这位老师的，解压下install就行了

**Comment by Cigarette30** [comment]
> 因为我的R是4.3的，然后bioconductor上的版本是说0.99.2适配＞=4.3的R，所以我用的是直接在bioconductor上下载的。不过，感谢你的回答，我回去试试老师的看看
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年11月02日 16:25 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [YuLab-SMU/HPO.db] I can't install HPO.db. (Issue #4) | 这个老师的版本是0.99.0，你的版本是哦0.99.2，就是有可能适配性不太好，你下载这位老师的，解压下install就行了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

怎么样，可以安装吗。

**Comment by Cigarette30** [comment]
> 这个老师的版本是0.99.0，你的版本是哦0.99.2，就是有可能适配性不太好，你下载这位老师的，解压下install就行了

您的意思是解压完放进library文件夹里吗？

**Comment by Cigarette30** [comment]
> 装上了，非常感谢您！

请问是下载解压后直接放进library的文件夹里吗？

**Comment by 1127yangyuping** [comment]
对呀，就那个解压gz安装那里



发自我的iPhone


------------------ Original ------------------
From: Cigarette30 ***@***.***&gt;
Date: Thu, Nov 2, 2023 10:41 PM
To: YuLab-SMU/HPO.db ***@***.***&gt;
Cc: 1127yangyuping ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [YuLab-SMU/HPO.db] I can't install HPO.db. (Issue #4)





  
装上了，非常感谢您！
  
请问是下载解压后直接放进library的文件夹里吗？

**Comment by qingyuyyy** [comment]
装上了！！！非常感谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月02日 22:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [YuLab-SMU/HPO.db] I can't install HPO.db. (Issue #4) |

因为我的R是4.3的，然后bioconductor上的版本是说0.99.2适配＞=4.3的R，所以我用的是直接在bioconductor上下载的。不过，感谢你的回答，我回去试试老师的看看
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年11月02日 16:25 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [YuLab-SMU/HPO.db] I can't install HPO.db. (Issue #4) | 这个老师的版本是0.99.0，你的版本是哦0.99.2，就是有可能适配性不太好，你下载这位老师的，解压下install就行了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>

怎么样，可以安装吗。

**Comment by QQRh** [comment]
* installing *source* package 'HPO.db' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'HPO.db':
 .onLoad failed in loadNamespace() for 'HPO.db', details:
  call: .updateHubDB(hub_bfc, .class, url, proxy, localHub)
  error: Invalid Cache: sqlite file
  Hub has not been added to cache
  Run again with 'localHub=FALSE'
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'D:/RRRR/R-4.3.2/library/HPO.db'
* restoring previous 'D:/RRRR/R-4.3.2/library/HPO.db'
 In install.packages(...) : 安装程序包‘HPO.db’时退出狀態的值不是0
Can someone email me a copy if it's convenient? Email Address：[2521536276@qq.com. ]Help me, please. Looking forward to your recovery!

**Comment by Huanghuangbiubiu** [comment]
> * installing _source_ package 'HPO.db' ...
>   ** using staged installation
>   ** R
>   ** inst
>   ** byte-compile and prepare package for lazy loading
>   ** help
>   *** installing help indices
>   ** building package indices
>   ** installing vignettes
>   ** testing if installed package can be loaded from temporary location
>   Error: package or namespace load failed for 'HPO.db':
>   .onLoad failed in loadNamespace() for 'HPO.db', details:
>   call: .updateHubDB(hub_bfc, .class, url, proxy, localHub)
>   error: Invalid Cache: sqlite file
>   Hub has not been added to cache
>   Run again with 'localHub=FALSE'
>   Error: loading failed
>   Execution halted
>   ERROR: loading failed
> * removing 'D:/RRRR/R-4.3.2/library/HPO.db'
> * restoring previous 'D:/RRRR/R-4.3.2/library/HPO.db'
>   In install.packages(...) : 安装程序包‘HPO.db’时退出狀態的值不是0
>   Can someone email me a copy if it's convenient? Email Address：[[2521536276@qq.com](mailto:2521536276@qq.com). ]Help me, please. Looking forward to your recovery!

我也是 下载了也没办法 现在正在下tools试试 下的真是太慢了 心疼网费呜呜呜呜

**Comment by Cigarette30** [comment]
你下载完怎么处理的？我直接用R install那个压缩包就可以了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuLab-SMU/HPO.db"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月4日(星期六) 晚上11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YuLab-SMU/HPO.db] I can't install HPO.db. (Issue #4)





   
installing source package 'HPO.db' ...
 ** using staged installation
 ** R
 ** inst
 ** byte-compile and prepare package for lazy loading
 ** help
 *** installing help indices
 ** building package indices
 ** installing vignettes
 ** testing if installed package can be loaded from temporary location
 Error: package or namespace load failed for 'HPO.db':
 .onLoad failed in loadNamespace() for 'HPO.db', details:
 call: .updateHubDB(hub_bfc, .class, url, proxy, localHub)
 error: Invalid Cache: sqlite file
 Hub has not been added to cache
 Run again with 'localHub=FALSE'
 Error: loading failed
 Execution halted
 ERROR: loading failed
 
removing 'D:/RRRR/R-4.3.2/library/HPO.db'
 
restoring previous 'D:/RRRR/R-4.3.2/library/HPO.db'
 In install.packages(...) : 安装程序包‘HPO.db’时退出狀態的值不是0
 Can someone email me a copy if it's convenient? Email ***@***.*** ]Help me, please. Looking forward to your recovery!
   
我也是 下载了也没办法 现在正在下tools试试 下的真是太慢了 心疼网费呜呜呜呜

**Comment by Huanghuangbiubiu** [comment]
> 你下载完怎么处理的？我直接用R install那个压缩包就可以了。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "YuLab-SMU/HPO.db" ***@***.***&gt;; 发送时间:&nbsp;2023年11月4日(星期六) 晚上11:15 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [YuLab-SMU/HPO.db] I can't install HPO.db. (Issue #4) installing source package 'HPO.db' ... ** using staged installation ** R ** inst ** byte-compile and prepare package for lazy loading ** help *** installing help indices ** building package indices ** installing vignettes ** testing if installed package can be loaded from temporary location Error: package or namespace load failed for 'HPO.db': .onLoad failed in loadNamespace() for 'HPO.db', details: call: .updateHubDB(hub_bfc, .class, url, proxy, localHub) error: Invalid Cache: sqlite file Hub has not been added to cache Run again with 'localHub=FALSE' Error: loading failed Execution halted ERROR: loading failed removing 'D:/RRRR/R-4.3.2/library/HPO.db' restoring previous 'D:/RRRR/R-4.3.2/library/HPO.db' In install.packages(...) : 安装程序包‘HPO.db’时退出狀態的值不是0 Can someone email me a copy if it's convenient? Email ***@***.*** ]Help me, please. Looking forward to your recovery! 我也是 下载了也没办法 现在正在下tools试试 下的真是太慢了 心疼网费呜呜呜呜 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我是下载完把hpo压缩包挪到library 然后解压后的也挪到了library 然后打开了"instl"，就不知道该点啥了，于是我又去r和r studio去library，显示不存在hpo压缩包

**Comment by 1127yangyuping** [comment]
下载这个老师的包，解压下，然后安装gz包就行了，不过版本是0.99.0的，因为老版本可能比较适配所以安装的比较容易，新版的可能因为R还有新版本适配性还有其他的原因，下载了并不一定能够安装



发自我的iPhone


------------------ Original ------------------
From: QQRh ***@***.***&gt;
Date: Sat, Nov 4, 2023 10:36 PM
To: YuLab-SMU/HPO.db ***@***.***&gt;
Cc: 1127yangyuping ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [YuLab-SMU/HPO.db] I can't install HPO.db. (Issue #4)





  
installing source package 'HPO.db' ...
 ** using staged installation
 ** R
 ** inst
 ** byte-compile and prepare package for lazy loading
 ** help
 *** installing help indices
 ** building package indices
 ** installing vignettes
 ** testing if installed package can be loaded from temporary location
 Error: package or namespace load failed for 'HPO.db':
 .onLoad failed in loadNamespace() for 'HPO.db', details:
 call: .updateHubDB(hub_bfc, .class, url, proxy, localHub)
 error: Invalid Cache: sqlite file
 Hub has not been added to cache
 Run again with 'localHub=FALSE'
 Error: loading failed
 Execution halted
 ERROR: loading failed
 
removing 'D:/RRRR/R-4.3.2/library/HPO.db'
 
restoring previous 'D:/RRRR/R-4.3.2/library/HPO.db'
 In install.packages(...) : 安装程序包‘HPO.db’时退出狀態的值不是0
 Can someone email me a copy if it's convenient? Email ***@***.*** ]Help me, please. Looking forward to your recovery!

**Comment by Huanghuangbiubiu** [comment]
> 下载这个老师的包，解压下，然后安装gz包就行了，不过版本是0.99.0的，因为老版本可能比较适配所以安装的比较容易，新版的可能因为R还有新版本适配性还有其他的原因，下载了并不一定能够安装 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: QQRh ***@***.***&gt; Date: Sat, Nov 4, 2023 10:36 PM To: YuLab-SMU/HPO.db ***@***.***&gt; Cc: 1127yangyuping ***@***.***&gt;, Comment ***@***.***&gt; Subject: Re: [YuLab-SMU/HPO.db] I can't install HPO.db. (Issue #4) installing source package 'HPO.db' ... ** using staged installation ** R ** inst ** byte-compile and prepare package for lazy loading ** help *** installing help indices ** building package indices ** installing vignettes ** testing if installed package can be loaded from temporary location Error: package or namespace load failed for 'HPO.db': .onLoad failed in loadNamespace() for 'HPO.db', details: call: .updateHubDB(hub_bfc, .class, url, proxy, localHub) error: Invalid Cache: sqlite file Hub has not been added to cache Run again with 'localHub=FALSE' Error: loading failed Execution halted ERROR: loading failed removing 'D:/RRRR/R-4.3.2/library/HPO.db' restoring previous 'D:/RRRR/R-4.3.2/library/HPO.db' In install.packages(...) : 安装程序包‘HPO.db’时退出狀態的值不是0 Can someone email me a copy if it's convenient? Email ***@***.*** ]Help me, please. Looking forward to your recovery! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

是的是的 我的r是4.3.1的，哎

**Comment by Cigarette30** [comment]
你说的方式我也尝试过，不起效。我建议你把所有library里的hpo文件都删除，然后重启软件，直接在R里install那个压缩包。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuLab-SMU/HPO.db"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月4日(星期六) 晚上11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YuLab-SMU/HPO.db] I can't install HPO.db. (Issue #4)





  
你下载完怎么处理的？我直接用R install那个压缩包就可以了。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "YuLab-SMU/HPO.db" @.&gt;; 发送时间:&nbsp;2023年11月4日(星期六) 晚上11:15 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [YuLab-SMU/HPO.db] I can't install HPO.db. (Issue #4) installing source package 'HPO.db' ... ** using staged installation ** R ** inst ** byte-compile and prepare package for lazy loading ** help *** installing help indices ** building package indices ** installing vignettes ** testing if installed package can be loaded from temporary location Error: package or namespace load failed for 'HPO.db': .onLoad failed in loadNamespace() for 'HPO.db', details: call: .updateHubDB(hub_bfc, .class, url, proxy, localHub) error: Invalid Cache: sqlite file Hub has not been added to cache Run again with 'localHub=FALSE' Error: loading failed Execution halted ERROR: loading failed removing 'D:/RRRR/R-4.3.2/library/HPO.db' restoring previous 'D:/RRRR/R-4.3.2/library/HPO.db' In install.packages(...) : 安装程序包‘HPO.db’时退出狀態的值不是0 Can someone email me a copy if it's convenient? Email @.*** ]Help me, please. Looking forward to your recovery! 我也是 下载了也没办法 现在正在下tools试试 下的真是太慢了 心疼网费呜呜呜呜 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
我是下载完把hpo压缩包挪到library 然后解压后的也挪到了library 然后打开了"instl"，就不知道该点啥了，于是我又去r和r studio去library，显示不存在hpo压缩包

**Comment by feidudu123** [comment]
> I'm trying to download HPO.db. I tried to open the link（[https://github.com/huerqiang/HPO.db_MPO.db）](https://github.com/huerqiang/HPO.db_MPO.db%EF%BC%89) but it won't download the file.
> 
> Webpage display [View raw] (Sorry about that, but we can’t show files that are this big right now.)
> 
> I do not know why. Can someone email me a copy if it's convenient? Email Address：[1158647287@qq.com](mailto:1158647287@qq.com). Help me, please. Looking forward to your recovery!

I met the same problem! Can someone email me a copy if it's convenient? Help me, Please. Email Address：1815333145@qq.com

**Comment by king991633** [comment]
I'm trying to download HPO.db. I tried to open the link（[https://github.com/huerqiang/HPO.db_MPO.db）](https://github.com/huerqiang/HPO.db_MPO.db%EF%BC%89) but it won't download the file.
Can someone email me HPO.db_0.99.0.tar.gz  Help me, Please. Email:11884654@qq.com

**Comment by huerqiang** [comment]
在Github地址里点击download zip应该是很好下载的。还有无法从Github下载并且没收到文件的吗，可以在我这条评论下留个邮箱，我统一发一下吧。

**Comment by feidudu123** [comment]
I have received your email and thank you very much for your help！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuLab-SMU/HPO.db"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月9日(星期四) 下午3:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YuLab-SMU/HPO.db] I can't install HPO.db. (Issue #4)





 
I'm trying to download HPO.db. I tried to open the link（https://github.com/huerqiang/HPO.db_MPO.db） but it won't download the file.
 Can someone email me HPO.db_0.99.0.tar.gz  Help me, Please. ***@***.***

**Comment by willingh-clinical** [comment]
错误: package or namespace load failed for ‘clusterProfiler’ in namespaceExport(ns, exports):
 出口不存在：HPO, HPO_dbconn, HPO_dbfile, HPO_dbschema, HPO_dbInfo
I have download HPO.db, but there is still another error. Could u please solve this problem? Thanks a lot.

**Comment by willingh-clinical** [comment]
@huerqiang

**Comment by huerqiang** [comment]
Reinstall the HPO.db.

**Comment by zhuli123-123** [comment]
> library(clusterProfiler)
错误: package or namespace load failed for ‘clusterProfiler’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 不存在叫‘DOSE’这个名字的程辑包
> BiocManager::install("DOSE")
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Bioconductor version 3.18 (BiocManager 1.30.22), R 4.3.2 (2023-10-31 ucrt)
Installing package(s) 'DOSE'
还安装相依关系‘MPO.db’, ‘HPO.db’

试开URL’https://bioconductor.org/packages/3.18/bioc/bin/windows/contrib/4.3/DOSE_3.28.0.zip'
Content type 'application/zip' length 7210741 bytes (6.9 MB)
downloaded 6.9 MB

程序包‘DOSE’打开成功，MD5和检查也通过

下载的二进制程序包在
	C:\Users\zl\AppData\Local\Temp\RtmpGqFZA0\downloaded_packages里
安装源码包‘MPO.db’, ‘HPO.db’

试开URL’https://bioconductor.org/packages/3.18/data/annotation/src/contrib/MPO.db_0.99.7.tar.gz'
Content type 'application/x-gzip' length 29300 bytes (28 KB)
downloaded 28 KB

试开URL’https://bioconductor.org/packages/3.18/data/annotation/src/contrib/HPO.db_0.99.2.tar.gz'
Content type 'application/x-gzip' length 24377 bytes (23 KB)
downloaded 23 KB

* installing *source* package 'MPO.db' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'MPO.db':
 .onLoad failed in loadNamespace() for 'MPO.db', details:
  call: .updateHubDB(hub_bfc, .class, url, proxy, localHub)
  error: Invalid Cache: sqlite file
  Hub has not been added to cache
  Run again with 'localHub=FALSE'
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'D:/software/R/R-4.3.2/library/MPO.db'
* installing *source* package 'HPO.db' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'HPO.db':
 .onLoad failed in loadNamespace() for 'HPO.db', details:
  call: .updateHubDB(hub_bfc, .class, url, proxy, localHub)
  error: Invalid Cache: sqlite file
  Hub has not been added to cache
  Run again with 'localHub=FALSE'
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'D:/software/R/R-4.3.2/library/HPO.db'

下载的程序包在
	‘C:\Users\zl\AppData\Local\Temp\RtmpGqFZA0\downloaded_packages’里
Warning messages:
1: In install.packages(...) : 安装程序包‘MPO.db’时退出狀態的值不是0
2: In install.packages(...) : 安装程序包‘HPO.db’时退出狀態的值不是0

**Comment by zhuli123-123** [comment]
老师，我下载不了那个文件，麻烦您发一下，2452261713@qq.com

**Comment by willingh-clinical** [comment]
老师我重新安装了HPO.db还是不行 @huerqiang

**Comment by huerqiang** [comment]
@willingh-clinical 看下前面的纪录安装本地版本的。

**Comment by miaomiaoyang1988** [comment]
老师，我下载了HPO.db_0.99.2安装不上，您能发一下HPO.db_0.99.0.tar.gz到我的邮箱吗(flyyang1880@163.com)，谢谢老师！ @huerqiang

**Comment by Tanyt98** [comment]
> 成员

老师，可以给我发一份嘛？谢谢！我的邮箱是1605612248@qq.com(麻烦老师啦！)
